# Generated by Django 5.0 on 2025-11-30 05:34

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(help_text='Enter your full name', max_length=150, verbose_name='Full Name')),
                ('email', models.EmailField(help_text='Your email address (used for login)', max_length=254, unique=True, verbose_name='Email Address')),
                ('role', models.CharField(choices=[('student', 'Student'), ('cr', 'Class Representative'), ('faculty', 'Faculty'), ('authority', 'Authority'), ('moderator', 'Moderator')], help_text='Your role in the system', max_length=20, verbose_name='Role')),
                ('phone', models.CharField(blank=True, help_text='Your contact phone number', max_length=20, null=True, verbose_name='Phone Number')),
                ('telegram_id', models.CharField(blank=True, help_text='Your Telegram username or ID', max_length=100, null=True, verbose_name='Telegram ID')),
                ('whatsapp_number', models.CharField(blank=True, help_text='Your WhatsApp number', max_length=20, null=True, verbose_name='WhatsApp Number')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the department', max_length=200, verbose_name='Department Name')),
                ('short_code', models.CharField(help_text='Short code for the department (e.g., CSE, ECE)', max_length=10, unique=True, verbose_name='Short Code')),
                ('description', models.TextField(blank=True, help_text='Description of the department', null=True, verbose_name='Description')),
                ('contact_emails', models.JSONField(blank=True, default=list, help_text='List of contact email addresses for the department', verbose_name='Contact Emails')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['short_code'], name='core_depart_short_c_5d972e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the faculty member', max_length=150, verbose_name='Name')),
                ('title', models.CharField(blank=True, help_text='Academic title (e.g., Professor, Associate Professor)', max_length=100, null=True, verbose_name='Title')),
                ('photo_url', models.URLField(blank=True, help_text="URL to the faculty member's photo", null=True, verbose_name='Photo URL')),
                ('biography', models.TextField(blank=True, help_text='Biography of the faculty member', null=True, verbose_name='Biography')),
                ('research_interests', models.TextField(blank=True, help_text='Research interests and areas of expertise', null=True, verbose_name='Research Interests')),
                ('contact_email', models.EmailField(blank=True, help_text='Contact email address', max_length=254, null=True, verbose_name='Contact Email')),
                ('office_hours', models.CharField(blank=True, help_text='Office hours information', max_length=200, null=True, verbose_name='Office Hours')),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20, null=True, verbose_name='Phone Number')),
                ('status', models.CharField(choices=[('active', 'Active'), ('retired', 'Retired')], default='active', max_length=20, verbose_name='Status')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_members', to='core.department', verbose_name='Department')),
            ],
            options={
                'verbose_name': 'Faculty',
                'verbose_name_plural': 'Faculty',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Notification title', max_length=200, verbose_name='Title')),
                ('body', models.TextField(help_text='Notification body content', verbose_name='Body')),
                ('push_to', models.JSONField(default=list, help_text='List of channels to push notification (email, telegram, whatsapp, web)', verbose_name='Push To')),
                ('scheduled_for', models.DateTimeField(blank=True, help_text='Schedule notification for a specific date and time', null=True, verbose_name='Scheduled For')),
                ('sent_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Sent Status')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('department', models.ForeignKey(blank=True, help_text='Leave blank for all departments', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.department', verbose_name='Department')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the study material', max_length=300, verbose_name='Title')),
                ('description', models.TextField(blank=True, help_text='Description of the study material', null=True, verbose_name='Description')),
                ('file_drive_id', models.CharField(blank=True, help_text='Google Drive file ID', max_length=255, null=True, verbose_name='File Drive ID')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('video', 'Video'), ('link', 'Link')], help_text='Type of the study material', max_length=20, verbose_name='File Type')),
                ('subject_tags', models.JSONField(blank=True, default=list, help_text='List of subject tags for categorization', verbose_name='Subject Tags')),
                ('semester', models.IntegerField(help_text='Semester number', verbose_name='Semester')),
                ('year', models.IntegerField(help_text='Academic year', verbose_name='Year')),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Verification Status')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Uploaded At')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Verified At')),
                ('downloads_count', models.IntegerField(default=0, verbose_name='Downloads Count')),
                ('thumbs_up_count', models.IntegerField(default=0, verbose_name='Thumbs Up Count')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_materials', to='core.department', verbose_name='Department')),
                ('uploader_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_materials', to=settings.AUTH_USER_MODEL, verbose_name='Uploader')),
                ('verifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_materials', to=settings.AUTH_USER_MODEL, verbose_name='Verifier')),
            ],
            options={
                'verbose_name': 'Study Material',
                'verbose_name_plural': 'Study Materials',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(help_text='Semester number', verbose_name='Semester')),
                ('course_code', models.CharField(help_text='Course code (e.g., CS101)', max_length=20, verbose_name='Course Code')),
                ('course_name', models.CharField(help_text='Full name of the course', max_length=200, verbose_name='Course Name')),
                ('date', models.DateField(help_text='Date of the class', verbose_name='Date')),
                ('start_time', models.TimeField(help_text='Class start time', verbose_name='Start Time')),
                ('end_time', models.TimeField(help_text='Class end time', verbose_name='End Time')),
                ('venue', models.CharField(help_text='Class venue or room number', max_length=100, verbose_name='Venue')),
                ('description', models.TextField(blank=True, help_text='Additional description or notes', null=True, verbose_name='Description')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='core.department', verbose_name='Department')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_entries', to='core.faculty', verbose_name='Instructor')),
            ],
            options={
                'verbose_name': 'Timetable Entry',
                'verbose_name_plural': 'Timetable Entries',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='UploadAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('upload', 'Upload'), ('edit', 'Edit'), ('delete', 'Delete')], max_length=20, verbose_name='Action')),
                ('reason', models.TextField(blank=True, help_text='Reason for the action', null=True, verbose_name='Reason')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.studymaterial', verbose_name='Study Material')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_actions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Upload Audit',
                'verbose_name_plural': 'Upload Audits',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('cr', 'Class Representative'), ('coordinator', 'Coordinator')], max_length=20, verbose_name='Role')),
                ('contact_info', models.TextField(blank=True, help_text='Additional contact information', null=True, verbose_name='Contact Info')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinator_roles', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinators', to='core.department', verbose_name='Department')),
            ],
            options={
                'verbose_name': 'Coordinator',
                'verbose_name_plural': 'Coordinators',
                'ordering': ['department', 'role', 'user'],
                'indexes': [models.Index(fields=['department', 'role'], name='core_coordi_departm_529667_idx')],
                'unique_together': {('user', 'department', 'role')},
            },
        ),
        migrations.AddIndex(
            model_name='faculty',
            index=models.Index(fields=['department', 'status'], name='core_facult_departm_b1d66a_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['department', 'sent_status'], name='core_notifi_departm_5c0fb8_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['scheduled_for', 'sent_status'], name='core_notifi_schedul_c56fbc_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_by'], name='core_notifi_created_852f30_idx'),
        ),
        migrations.AddIndex(
            model_name='studymaterial',
            index=models.Index(fields=['department', 'semester', 'year'], name='core_studym_departm_1c7e38_idx'),
        ),
        migrations.AddIndex(
            model_name='studymaterial',
            index=models.Index(fields=['verification_status'], name='core_studym_verific_9b5590_idx'),
        ),
        migrations.AddIndex(
            model_name='studymaterial',
            index=models.Index(fields=['uploader_user'], name='core_studym_uploade_69add7_idx'),
        ),
        migrations.AddIndex(
            model_name='timetableentry',
            index=models.Index(fields=['department', 'semester', 'date'], name='core_timeta_departm_422411_idx'),
        ),
        migrations.AddIndex(
            model_name='timetableentry',
            index=models.Index(fields=['date', 'start_time'], name='core_timeta_date_46d5b4_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadaudit',
            index=models.Index(fields=['material', 'timestamp'], name='core_upload_materia_2e8e2c_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadaudit',
            index=models.Index(fields=['uploader', 'timestamp'], name='core_upload_uploade_c0b9f2_idx'),
        ),
    ]
