# Generated by Django 5.0 on 2025-11-30 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Views Count'),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='downloads_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Downloads Count'),
        ),
        migrations.CreateModel(
            name='SearchQueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(help_text='The search query entered by the user', max_length=255, verbose_name='Search Query')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the search (if authenticated)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_queries', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Search Query Log',
                'verbose_name_plural': 'Search Query Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='core_search_timesta_e03719_idx'), models.Index(fields=['user', '-timestamp'], name='core_search_user_id_1d13a8_idx')],
            },
        ),
    ]
