# Generated by Django 5.0 on 2025-11-30 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_studymaterial_views_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='favorites_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of users who favorited this material', verbose_name='Favorites Count'),
        ),
        migrations.CreateModel(
            name='RecentlyViewedMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_viewed_at', models.DateTimeField(auto_now=True, help_text='When this material was last viewed by the user', verbose_name='Last Viewed At')),
                ('material', models.ForeignKey(help_text='The study material that was viewed', on_delete=django.db.models.deletion.CASCADE, related_name='recent_views', to='core.studymaterial', verbose_name='Study Material')),
                ('user', models.ForeignKey(help_text='User who viewed this material', on_delete=django.db.models.deletion.CASCADE, related_name='recently_viewed_materials', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Recently Viewed Material',
                'verbose_name_plural': 'Recently Viewed Materials',
                'ordering': ['-last_viewed_at'],
                'indexes': [models.Index(fields=['user', '-last_viewed_at'], name='core_recent_user_id_8a4d32_idx'), models.Index(fields=['-last_viewed_at'], name='core_recent_last_vi_7ce72f_idx'), models.Index(fields=['material'], name='core_recent_materia_a64603_idx')],
                'unique_together': {('user', 'material')},
            },
        ),
        migrations.CreateModel(
            name='UserFavoriteMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this material was favorited', verbose_name='Created At')),
                ('material', models.ForeignKey(help_text='The study material that was favorited', on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='core.studymaterial', verbose_name='Study Material')),
                ('user', models.ForeignKey(help_text='User who favorited this material', on_delete=django.db.models.deletion.CASCADE, related_name='favorite_materials', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Favorite Material',
                'verbose_name_plural': 'User Favorite Materials',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='core_userfa_user_id_92d962_idx'), models.Index(fields=['material'], name='core_userfa_materia_9b2bfc_idx')],
                'unique_together': {('user', 'material')},
            },
        ),
    ]
